In [69]:
import cv2
import numpy as np
 
img = cv2.imread("E:\\GITHUB\\Image_Operations\\ROI\\Flowers.jpg", cv2.IMREAD_COLOR)
print(img.shape)
print('\n')
print(img)


(1000, 1600, 3)


[[[28 53 25]
  [21 46 18]
  [18 45 19]
  ...
  [30 60 41]
  [32 62 43]
  [33 63 44]]

 [[32 57 29]
  [25 53 24]
  [23 50 24]
  ...
  [29 59 40]
  [31 61 42]
  [32 62 43]]

 [[30 57 31]
  [28 55 29]
  [26 52 28]
  ...
  [27 59 40]
  [28 60 41]
  [29 61 42]]

 ...

 [[ 3  3  3]
  [ 3  3  3]
  [ 2  2  2]
  ...
  [18 20 14]
  [20 20 14]
  [20 20 14]]

 [[ 5  5  5]
  [ 4  4  4]
  [ 3  3  3]
  ...
  [20 22 16]
  [22 22 16]
  [22 22 16]]

 [[ 6  6  6]
  [ 5  5  5]
  [ 4  4  4]
  ...
  [21 23 17]
  [23 23 17]
  [24 24 18]]]


In [70]:
img = cv2.resize(img, (700,400))
img.shape

(400, 700, 3)

In [71]:
ROI = img[245: 400, 145:328]


In [ ]:
cv2.imshow("Resized Image",img)
cv2.imshow("ROI",ROI)
cv2.waitKey()
cv2.destroyAllWindows()