In [190]:

import cv2
import numpy as np
 
img = cv2.imread("E:\\GITHUB\\Image_Operations\\Drawing_on_Images\\Cat.jpg", cv2.IMREAD_COLOR)
print(img.shape)
print('\n')
print(img)

(1200, 1600, 3)


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [246 236 248]
  [240 230 242]
  [235 225 237]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [248 238 250]
  [242 232 244]
  [235 225 237]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [251 241 253]
  [248 238 250]
  [242 232 244]]

 ...

 [[251 245 250]
  [251 245 250]
  [251 245 250]
  ...
  [231 224 231]
  [235 228 235]
  [238 231 238]]

 [[250 246 251]
  [250 246 251]
  [250 246 251]
  ...
  [235 228 235]
  [233 226 233]
  [231 224 231]]

 [[253 249 254]
  [253 249 254]
  [253 249 254]
  ...
  [232 225 232]
  [227 220 227]
  [221 214 221]]]


In [191]:
img = cv2.resize(img, (700,400))
img.shape

(400, 700, 3)

In [192]:
blue = (255, 0, 0)
red = (0, 0, 255)
green = (0, 255, 0)
violet = (180, 0, 180)


In [193]:
cv2.line(img, (440, 170), (588, 192), blue, thickness=5)
cv2.circle(img, (476, 268), 10, red, -1)
cv2.rectangle(img, (440, 70), (588, 150), violet, -1)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [240, 230, 242],
        [248, 238, 250],
        [239, 229, 241]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [254, 244, 255],
        [241, 231, 243],
        [251, 242, 252]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [232, 222, 234],
        [251, 242, 253],
        [249, 239, 251]],

       ...,

       [[251, 245, 250],
        [251, 245, 250],
        [251, 245, 250],
        ...,
        [226, 219, 226],
        [240, 233, 240],
        [237, 230, 237]],

       [[254, 248, 253],
        [254, 248, 253],
        [254, 248, 253],
        ...,
        [230, 223, 230],
        [219, 212, 219],
        [225, 218, 225]],

       [[250, 246, 251],
        [250, 246, 251],
        [250, 246, 251],
        ...,
        [228, 221, 228],
        [234, 227, 234],
        [232, 225, 232]]

In [194]:
cv2.imshow("Output Image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()